### ISSUE TITLE
Undeclared subroutines `fill` and `wrap`

### ISSUE THREAD

**Issue by paultcochrane** [Altai-man/perl6-Text-Tabs#1]
The subroutines `fill` and `wrap` are used in the `20-sane.t` tests, however they are undefined:

```
t/20-sane.t .. ===SORRY!=== Error while compiling perl6-Text-Tabs/t/20-sane.t
Undeclared routines:
    fill used at line 12
    wrap used at line 11
```

They were removed in 05397a14e5e5c1c0a0a8623b5fe4e7e285af05aa, and it looks like the test suite hasn't passed since then.  Unfortunately, I don't have a fix, however I thought you'd like to know about the problem.

**Comment by Altai-man** [comment]
Oh, thanks for your noticing!

Travis wasn't set up for this package and it was in a somewhat unstable state, since `Text::Wrap` was implemented in another package before I finished it(not a bit issue, anyway).

I'll remove this calls and set up travis tomorrow or so. It's a pity that I didn't have much free time to maintain my packages and some dust was gathered

**Comment by paultcochrane** [comment]
Actually, I was in the process of setting up Travis and noticed the test failures and thought I'd let you know before submitting the next patch: a Travis config :-)  If you want, I can still submit the Travis config patch; just let me know.

**Comment by Altai-man** [comment]
Yeah, it will be just great. I'll just add logo into the readme then. :+1:

**Comment by paultcochrane** [comment]
Here 'tis :-)

**Comment by Altai-man** [comment]
Thanks for your attention, fixed!
